#!/usr/bin/env bash
# Setup my ssh alias.
# ...
# After executing this script, you will only have to type <ssh [YOUR_ALIAS]>
# and you will be able to connect to your server without writing anything else.

if [ $# != 4 ]
then
    echo "USAGE: ./setup_alias_ssh ALIAS USER IP SSH_KEY_PATH"
    exit
fi

my_server="\n\
Host $1\n\
    HostName $3\n\
    User $2\n\
    IdentityFile $4\n\
    PasswordAuthentication no"
    
sudo echo -e "$my_server" >> /etc/ssh/ssh_config
